name: CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  workflow_dispatch:

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run if test success
        if: steps.test.conclusion == 'success'
        run: echo "Test Success!"
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  random-number-generator:
    runs-on: ubuntu-latest
    outputs:
      number: ${{ steps.generate-number.outputs.number }}
    steps:
      - id: generate-number
        run: echo "number=$(echo $RANDOM)" >> "$GITHUB_OUTPUT"
      - id: is-even
          echo "is-even=$(${{steps.generate-number.outputs.number}} % 2 == 0)" >> "$GITHUB_OUTPUT"
          echo "The number is ${{steps.generate-number.outputs.number}}" >> $GITHUB_STEP_SUMMARY
  
  consumer-of-generator:
    needs: random-number-generator
    runs-on: ubuntu-latest
    steps:
      - run: echo "The number is ${{ needs.random-number-generator.outputs.number }}"
  
  consumer-of-generator-odd:
    needs: random-number-generator
    runs-on: ubuntu-latest
    if: ${{ ! needs.random-number-generator.outputs.is-even }}
    steps:
      - run: echo "The number is ${{ needs.random-number-generator.outputs.number }} is odd"

  consumer-of-generator-even:
    needs: random-number-generator
    runs-on: ubuntu-latest
    if: ${{ needs.random-number-generator.outputs.is-even }}
    steps:
      - run: echo "The number is ${{ needs.random-number-generator.outputs.is-even }} is even"
